<?xml version="1.0" encoding="utf-8"?><Database Name="ShopYame" Class="DataShopYameDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ShopYame;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ShopYameConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="MaAdmin" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SoLuongBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChatLieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KichThuoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MauSac" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenChiTietLoaiSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETDONDATHANG" Member="CHITIETDONDATHANGs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="CHITIETDONDATHANG" />
      <Association Name="SANPHAM_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="CHITIETSANPHAM" />
      <Association Name="SANPHAM_DANHMUCHINH" Member="DANHMUCHINHs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="DANHMUCHINH" />
      <Association Name="SANPHAM_KHUYENMAI" Member="KHUYENMAIs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="KHUYENMAI" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="LOAISANPHAM" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="LOAISANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETDONDATHANG" Member="CHITIETDONDATHANGs">
    <Type Name="CHITIETDONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETDONDATHANG" Member="SANPHAM" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="DONDATHANG_CHITIETDONDATHANG" Member="DONDATHANG" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DONDATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETSANPHAM" Member="CHITIETSANPHAMs">
    <Type Name="CHITIETSANPHAM">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnhBia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETSANPHAM" Member="SANPHAM" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="KHACHHANG_CHITIETSANPHAM" Member="KHACHHANG" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUCHINH" Member="DANHMUCHINHs">
    <Type Name="DANHMUCHINH">
      <Column Name="MaHinh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HinhSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SANPHAM_DANHMUCHINH" Member="SANPHAM" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONDATHANG" Member="DONDATHANGs">
    <Type Name="DONDATHANG">
      <Column Name="MaDonHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DONDATHANG_CHITIETDONDATHANG" Member="CHITIETDONDATHANGs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="CHITIETDONDATHANG" />
      <Association Name="KHACHHANG_DONDATHANG" Member="KHACHHANG" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="KHACHHANG_CHITIETSANPHAM" Member="CHITIETSANPHAMs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="CHITIETSANPHAM" />
      <Association Name="KHACHHANG_DONDATHANG" Member="DONDATHANGs" ThisKey="MaKhachHang" OtherKey="MaKhachHang" Type="DONDATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MaKM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HinhKM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaTriKM" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="SANPHAM_KHUYENMAI" Member="SANPHAM" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MaLoaiSanPham" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiSanPham" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="MaLoaiSanPham" OtherKey="MaLoaiSanPham" Type="SANPHAM" />
    </Type>
  </Table>
</Database>